Added files validation
Big-Life-Lab/PHES-ODM pull request #253
Opened 2023-06-23 15:13 UTC by rvyuha

The focus of this PR is the initial files sheet validation.
The following changes can be found:

- files-validation.R contains the main function used for the dictionary automation.
- files.R contains the hardcoded strings used to interface with the files sheet.
- tests/ Contains test files.
- data/test-data/ Contains test excel files.
- .github/workflows/update-documentation.yml new github action workflow to trigger the automation workflow.

2023-06-23 15:13 UTC, rvyuha commented
@yulric ready for review

2023-06-25 12:23 UTC, yulric requested changes
* Can we move all the files for the R project into its own folder within the repo? To contain the R project in a single folder and not pollute the dictionary repo.
* Can you add additional tests for the following validations:
* Test if a mandatory column is not present it throws an error (eg., fileID)
* Test if the value in a mandatory column is not present it throws an error (eg., fileID)
* Test if the value in a category column is not one of the categories, it throws an error (eg., destinations)
* Can you try to write each test so that its only testing one thing?
* For example, the warning with incorrect fileType is testing two things:
	* Its testing that an error is generated if a CSV file has a set as its part
	* Its testing that an error is generated if a set in an excel file is not present
* These will allow each test to be as small as possible, making it easy to debug why a test failed
* Can you try to write the test description in a human readable way? For example,
* standard run with no issues -> If the user passes in a dictionary with a valid files sheet, it should not throw an errors
* warning with incorrect filetype -> If the user passed in a dictionary where the part column in the files sheet is invalid, it should throw an error
* Should files-validation.R be renamed to create-release-files.R since that's the main function?

2023-06-25 12:23 UTC, yulric commented on R/files-validation.R
> +  for (row_index in 1:nrow(files_sheet_formatted)) {
Use `seq_len` in case there are 0 rows?

2023-06-25 12:23 UTC, yulric commented on R/files-validation.R
> +      sets_info <- sets_sheet[sets_sheet$setID == partID, "partID"]
Why are you pulling out the `partID` column here?

2023-06-25 12:23 UTC, yulric commented on R/files-validation.R
> +          paste0(errors,
Can we add more information to the errors? For example the `fileID`? To make it easy for the user to know where the error is.

2023-06-25 12:23 UTC, yulric commented on R/files-validation.R
> +    if (fileType == files$file_type$categories$csv) {
Shouldn't you also check if it is a part, that it exists in the part sheet?

2023-06-25 12:23 UTC, yulric commented on R/files-validation.R
> +        errors <-
The `partID` column for an excel sheet can also be a part, it doesn't have to be a set. https://github.com/Big-Life-Lab/PHES-ODM/blob/release-automation/specs/release-automation/release-automation-specs.qmd#L230

2023-06-25 12:23 UTC, yulric commented on R/files.R
> +files <- list(
Rename to `files_sheet`

2023-06-25 12:23 UTC, yulric commented on R/files.R
> +  osf_locations = list(
osf_locations -> osf_location

2023-06-25 12:23 UTC, yulric commented on R/odm-dictionary-file.R
> +odm_dictionary$dictionary_directory <- "data/raw"
Aren't the first two variables (dictionary_directory and tmp_dictionary_directory) not applicable to an ODM dictionary but only to the automation? If so, it should be moved to the files-validation.R file.

2023-06-25 12:23 UTC, yulric commented on R/odm-dictionary-file.R
> +odm_dictionary$dictionary_missing_value_replacement <- "NA"
Is this used?

2023-06-25 12:23 UTC, yulric commented on .github/update-documentation.yml
> +name: Update Documentation
Not sure Update Documentation makes sense as the name. Maybe something like `Create Release`

2023-08-15 15:11 UTC, closed without merging